### ISSUE TITLE
Cmake fails to find boost_python36

### ISSUE THREAD

**Issue by mkuiack** [aroffringa/aartfaac2ms#4]
Installing this within  the LOFAR cookbook singularity image kept giving "Could not find boost_python36"
I downloaded latest Boost 1.61, still didn't work. Then had to roll to python 2.7 

After these edits to CMakeList.txt installation was successful.

```bash
set(CASACORE_ROOT_DIR /opt/lofarsoft)
set(AOFLAGGER_INCLUDE_DIR /opt/lofarsoft/include)
set(AOFLAGGER_LIB /opt/lofarsoft/lib/libaoflagger.so.0)
set(BOOST_ROOT ~/soft/src/boost_1_61_0)
set(BOOST_PYTHONLIB python)

find_package(PythonLibs 2.7 REQUIRED)
find_package(PythonInterp 2.7 REQUIRED)
```

then make with
```bash 
cmake .. \
-DPYTHON_INCLUDE_DIR=/opt/lofarsoft/include/ \
-DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0````

**Comment by aroffringa** [comment]
Hi @mkuiack . Boost_python is pretty messy and unfortunately might require some editting on some distributions due to different distributions naming boost_python differently (e.g. boost_python3, boost_python36, boost_python3_py36, etc.). I haven't come up with a good solution, so I don't know how to fix this for you. The current branch compiles on new version of Ubuntu and Debian, which if I have to chose I'll support. Good news is that we're switching most tools to pybind11, which solves most of these issues. 

Thanks for reporting though ; it's good to know.
